/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package senai.cronos.gui;

import java.awt.Component;
import java.util.List;
import javax.swing.JDialog;
import senai.cronos.CronosAPI;
import senai.cronos.entidades.Docente;
import senai.cronos.gui.custom.LinkEffectHandler;
import senai.cronos.gui.custom.ProficienciaSlider;

/**
 *
 * @author Sergio
 */
public class DocenteProficienciaUI extends javax.swing.JPanel {

    /**
     * Creates new form DocenteProficienciaUI
     */
    public DocenteProficienciaUI(JDialog container, Docente doc, List<ProficienciaSlider> sliders) {
        initComponents();

        lbOK.addMouseListener(new LinkEffectHandler());

        for (ProficienciaSlider slider : sliders) {
            pnProficiencias.add(slider);
        }

        this.container = container;
        this.doc = doc;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        magicScroll1 = new br.ufrpe.bcc.continuous.components.MagicScroll();
        pnProficiencias = new javax.swing.JPanel();
        lbOK = new javax.swing.JLabel();
        lbstatus = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(650, 447));
        setMinimumSize(new java.awt.Dimension(650, 447));

        magicScroll1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_AS_NEEDED);

        pnProficiencias.setMaximumSize(new java.awt.Dimension(630, 32767));
        pnProficiencias.setMinimumSize(new java.awt.Dimension(630, 350));
        pnProficiencias.setPreferredSize(new java.awt.Dimension(630, 1300));
        magicScroll1.setViewportView(pnProficiencias);

        lbOK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbOK.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("senai/cronos/gui/Bundle"); // NOI18N
        lbOK.setText(bundle.getString("DocenteProficienciaUI.lbOK.text")); // NOI18N
        lbOK.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        lbOK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbOKMouseClicked(evt);
            }
        });

        lbstatus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbstatus.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbstatus.setText(bundle.getString("DocenteProficienciaUI.lbstatus.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbOK, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbstatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(magicScroll1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(magicScroll1, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbOK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbstatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lbOKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbOKMouseClicked
        new Thread(new Runnable() {
            public void run() {
                try {                    
                    CronosAPI.update(doc);
                    container.dispose();
                } catch (Exception ex) {
                    Alerta.jogarAviso(ex.getMessage());
                }

            }
        }).start();
        lbOK.setVisible(false);
        lbstatus.setText("Atualizando, aguarde...");
        pnProficiencias.removeAll();
        
    }//GEN-LAST:event_lbOKMouseClicked
    
    private Docente doc;
    private JDialog container;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbOK;
    private javax.swing.JLabel lbstatus;
    private br.ufrpe.bcc.continuous.components.MagicScroll magicScroll1;
    private javax.swing.JPanel pnProficiencias;
    // End of variables declaration//GEN-END:variables
}
