/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Update.java
 *
 * Created on 27/01/2012, 09:59:02
 */
package senai.cronos.gui;

import javax.swing.JLabel;
import javax.swing.JProgressBar;

/**
 *
 * @author Carlos Melo
 */
public class Update extends javax.swing.JPanel {

    /** Creates new form Update */
    public Update() {
        initComponents();
    }

    public JProgressBar getProgresso() {
        return progresso;
    }

    public void setProgresso(int i) {
         progresso.setValue(i);
    }
    public void iniciarBarra(){
        progresso.setMinimum(0);
        progresso.setMinimum(100);
    }

    public JLabel getAtualiza() {
        return atualiza;
    }

    public void setAtualiza(String frase) {
        this.atualiza.setText(frase);
    }

    public void setTitulo(String teste) {
        this.titulo.setText(teste);
    }
    
   

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane2 = new javax.swing.JLayeredPane();
        progresso = new javax.swing.JProgressBar();
        atualiza = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(450, 250));
        setMinimumSize(new java.awt.Dimension(450, 250));
        setName(""); // NOI18N

        progresso.setBounds(20, 90, 400, 40);
        jLayeredPane2.add(progresso, javax.swing.JLayeredPane.DEFAULT_LAYER);

        atualiza.setFont(new java.awt.Font("Segoe UI", 0, 14));
        atualiza.setBounds(20, 150, 390, 20);
        jLayeredPane2.add(atualiza, javax.swing.JLayeredPane.DEFAULT_LAYER);

        titulo.setFont(new java.awt.Font("Segoe UI", 0, 18));
        titulo.setText("Atualizando o Sistema");
        titulo.setBounds(20, 40, 350, 35);
        jLayeredPane2.add(titulo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane1.setMaximumSize(new java.awt.Dimension(450, 250));
        jLayeredPane1.setMinimumSize(new java.awt.Dimension(450, 250));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/senai/cronos/gui/images/background.png"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(450, 250));
        jLabel2.setMinimumSize(new java.awt.Dimension(450, 250));
        jLabel2.setName(""); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(450, 250));
        jLabel2.setBounds(0, 0, 450, 300);
        jLayeredPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane1.setBounds(0, 0, 450, 250);
        jLayeredPane2.add(jLayeredPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel atualiza;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JProgressBar progresso;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
